@startuml
!include <C4/C4_Component>

title C4 Component Diagram voor TripTop

System_Boundary(triptop_core, "TripTop") {

Component(HotelController, "HotelController", "Spring Boot Java Class", "Controller voor het vinden van hotels")
Component(HotelService, "HotelService", "Spring Boot Java Class", "Service voor het verwerken van een API aanroep naar de endpoint")
Component(HotelRepository, "HotelRepository", "Spring Boot Java Class", "Klasse om ervoor te zorgen dat de API Request correct wordt gestuurd met juiste gegevens")
Component(BookingRepo, "BookingRepo", "Spring Boot Java Class", "Klasse voor het ophalen van gegevens uit de Booking.com API")
Component(TripAdvisorRepo, "TripAdvisorRepo", "Spring Boot Java Class", "Klasse voor het ophalen van gegevens uit de Trip Advisor API")
}

System_Ext(Booking, "Booking.com API", "Externe API voor het ophalen van hotelgegevens")
System_Ext(TripAdvisor, "Trip Advisor API", "Externe API voor het ophalen van hotelgegevens")

Rel("HotelController", "HotelService", "Geeft de API request door naar de service")
Rel("HotelService", "HotelRepository", "Geeft de (aangepaste) API request door aan de API Gateway")
Rel("HotelRepository", "BookingRepo", "Geeft de API request op de juiste manier door zodat de externe API er wat mee kan")
Rel("HotelRepository", "TripAdvisorRepo", "Geeft de API request op de juiste manier door zodat de externe API er wat mee kan")
Rel("BookingRepo", "Booking", "Haal gegevens uit")
Rel("TripAdvisorRepo", "TripAdvisor", "Haal gegevens uit")
@enduml