@startuml

abstract class ApiCaller {
    + roepExternaApiAan()
    Login() {abstract}
    ApiCal() {abstract}
    TokenCheck() {abstract}
}

interface RestaurentPort {
  +  retrieveData() : List<RestaurantDTO>
}

interface ActiviteitenPort {
  +  retrieveData() : List<AcitivteitDTO>
}

class RestaurentController {
  - restaurentService
  + getAllRestaurantsInArea(): List<RestaurantDTO>
}

class ActiviteitenController {
  - ActiviteitenService
  + getActivities(opt String zoekwoord)
}

class RestaurentService {
  - restaurantports:List<IRestaurantPort>
  + getAllRestaurants():List<RestaurantDTO>
}

class ActiviteitenService {
  + processActivityData()
}

class UberEatsScraperAdapt  {
}

class TripAdvicorScraperAdapt  {
}

class ActiviteitenAdapt {
}

class RestaurantDTO{
    + name: String
    + latitude: double
    + longitude: double
    + address: String
    + phoneNumber: String
}

Frontend ..> RestaurentController : "calls"
Frontend ..> ActiviteitenController : "calls"

RestaurentController --> RestaurentService : "heeft"
ActiviteitenController --> ActiviteitenService : "heeft"

RestaurentService --> UberEatsScraperAdapt  : "queries"
RestaurentService --> TripAdvicorScraperAdapt : "queries"
ActiviteitenService --> ActiviteitenAdapt : "queries"

UberEatsScraperAdapt  ..|> RestaurentPort : "implements"
TripAdvicorScraperAdapt ..|> RestaurentPort : "implements"
ActiviteitenAdapt ..|> ActiviteitenPort : "implements"

UberEatsScraperAdapt  --|> ApiCaller : "extends"
TripAdvicorScraperAdapt --|> ApiCaller : "extends"
ActiviteitenAdapt --|> ApiCaller : "extends"

RestaurentPort --> RestaurantDTO : maakt aan
ActiviteitenPort --> ActivteitenDTO: maakt aan

@enduml
