@startuml

abstract class ApiCaller {
    + roepExternaApiAan()
    Login() {abstract}
    ApiCal() {abstract}
    TokenCheck() {abstract}
}

interface RestaurantPort {
  +  retrieveData() : List<RestaurantDTO>
}

interface ActiviteitenPort {
  +  retrieveData() : List<AcitivteitDTO>
}

class RestaurantController {
  - restaurantService : RestaurantService
  + getAllRestaurantsInArea(): List<RestaurantDTO>
}

class ActiviteitenController {
  - activiteitenService : ActiviteitenService
  + getActivities(opt String zoekwoord)
}

class RestaurantService {
  - restaurantports:List<IRestaurantPort>
  + getAllRestaurants():List<RestaurantDTO>
}

class ActiviteitenService {
  + processActivityData()
}

class UberEatsScraperAdapt  {
}

class TripAdvisorScraperAdapt  {
}

class ActiviteitenAdapt {
}

class RestaurantDTO{
    + name: String
    + latitude: double
    + longitude: double
    + address: String
    + phoneNumber: String
}

Frontend ..> RestaurantController : "calls"
Frontend ..> ActiviteitenController : "calls"

RestaurantController --> RestaurantService : "heeft"
ActiviteitenController --> ActiviteitenService : "heeft"

RestaurantService --> UberEatsScraperAdapt  : "queries"
RestaurantService --> TripAdvisorScraperAdapt : "queries"
ActiviteitenService --> ActiviteitenAdapt : "queries"

UberEatsScraperAdapt  ..|> RestaurantPort : "implements"
TripAdvisorScraperAdapt ..|> RestaurantPort : "implements"
ActiviteitenAdapt ..|> ActiviteitenPort : "implements"

UberEatsScraperAdapt  --|> ApiCaller : "extends"
TripAdvisorScraperAdapt --|> ApiCaller : "extends"
ActiviteitenAdapt --|> ApiCaller : "extends"

RestaurantPort --> RestaurantDTO : maakt aan
ActiviteitenPort --> ActivteitenDTO: maakt aan

@enduml
