@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include <C4/C4_Container>

title C4 Container Diagram voor Inloggen op TripTop

LAYOUT_WITH_LEGEND()

SHOW_PERSON_OUTLINE()

Person(Reiziger, "Reiziger", "Een reiziger die zonder zorgen op reis wil.")
Person(Reisagent, "Reisagent", "Helpt met de reis plannen voor andere reizigers")

Container_Ext(fbLogin, "Facebook Media API", "Zorgt voor het inloggen via Facebook")
Container_Ext(fbVerify, "Facebook Graph API", "haalt de gegevens van fb op")



System_Boundary(triptop_core, "TripTop") {
    Container(backend, "TripTop Back-end", "Java", "Verwerken, controleren en aanpassen van API requests vanuit de web applicatie")
    Container(db, "TripTop Database", "MSSQL", "Opslag van gegevens")
    Container(triptop, "TripTop Web Applicatie", "React", "User interface voor het plannen, boeken en bijhouden van vakanties")

}

Reiziger --> triptop : "Logt in op website (1)"
triptop --> backend : "stuurt inloggegevens ter controle[Json](2)"
backend --> db : "Controleerd inloggegevens(3)"
backend --> triptop : "Slaat de JWT-token op in de Session(4, 5A)"
triptop --> triptop : "laat de username zien, en vervangt de login voor logout.(5,6A)"

Reisagent --> triptop : "Logt in op website(1)"


Reiziger --> fbLogin : "Logt in via facebook(1A)"
Reisagent --> fbLogin : "Logt in via Facebook(1A)"
fbLogin --> fbVerify : "verifieerd met FBaccess token(2A)"
fbVerify --> backend : "stuur gegevens door[Json](3A)"

backend --> backend : "Genereert JWT na verificatie van facebook(4A)"


@enduml