@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include <C4/C4_Container>

title C4 Container Diagram voor Inloggen op TripTop

LAYOUT_WITH_LEGEND()

SHOW_PERSON_OUTLINE()

Person(Reiziger, "Reiziger", "Een reiziger die zonder zorgen op reis wil.")
Person(Reisagent, "Reisagent", "Helpt met de reis plannen voor andere reizigers")

Container_Ext(fbLogin, "Facebook Media API", "Zorgt voor het inloggen via Facebook")
Container_Ext(id, "Login - Signup API", "Een applicatie voor het identificeren en authoriseren van een gebruiker")
Container_Ext(fbVerify, "Facebook Graph API", "haalt de gegevens van fb op")


System_Boundary(triptop_core, "TripTop") {
    Container(backend, "TripTop Back-end", "Java", "Verwerken, controleren en aanpassen van API requests vanuit de web applicatie")
    Container(db, "TripTop Database", "MSSQL", "Opslag van gegevens")
}

Reiziger --> id : "Logt in op website"
Reisagent --> id : "Logt in op website"
Reiziger --> fbLogin : "Logt in op website"
Reisagent --> fbLogin : "Logt in via Facebook"

id --> backend : "verifieerd met JWT Token"
backend --> db : "Controleerd inloggegevens"
backend --> backend : "Genereert JWT na verificatie van facebook"
fbLogin --> fbVerify : "verifieerd met FBaccess token"
fbVerify --> backend : "stuur gegevens door in Json"


@enduml