@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml


title Context Diagram TripTop

LAYOUT_WITH_LEGEND()

SHOW_PERSON_OUTLINE()
Person(Reiziger, "Reiziger", "Een reiziger die zonder zorgen op reis wil.")
Person(Reisagent, "Reisagent", "Helpt met de reis plannen voor andere reizigers")

System_Boundary(triptop_core, "TripTop") {
    System(triptop, "TripTop", "Reisplatform voor reisplanning.")
}

System_Ext(betaalsysteem, "Betaalsysteem", "Externe betaalprovider.")
System_Ext(reisAanbieder, "ReisAanbieder", "busMaatschappij, Trein schema's, luchtvaartmaatschappijen, etc.")
System_Ext(etenAanbieder, "EetAanbieder", "kan eten bestellen via bijv: uber eats, just eat")
System_Ext(AutoAanbieder, "AutoAanbieder", "Auto of fiets verhuur")
System_Ext(Dagbesteding, "Dagbesteding", "Heeft tickets voor dagjes uit")
System_Ext(GoogleMaps, "GoogleMaps", Heeft de kaart waar alles op gesplaatst kan worden)

Reiziger --> triptop : Boekt reis
Reisagent --> triptop : Boekt reis voor andere


triptop --> betaalsysteem : Verwerkt betaling
triptop --> reisAanbieder : Reserveert reis naar locatie
triptop --> etenAanbieder : Kan eten bestellen
triptop --> AutoAanbieder : Kan een vervoer huren bij
triptop --> Dagbesteding : kan dagjes plannen
triptop --> GoogleMaps : laat activiateiten zien op
@enduml
