@startuml
!include <C4/C4_Container>
!include <C4/C4_Component>
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Container("frontend", "Frontend", "Container met React.js", "Zorgt voor frontend en de gebruikersinterfaces")

System_Boundary(triptop_core, "TripTop") {
Component("restaurentController1", "restaurentController","SpringBoot","Controller voor een restaurantscraper")
Component("restaurentService1", "restaurentService","SpringBoot","Controller voor een restaurantscraper")
Component("RestaurantApi1Implementatie", "UberEastScraperAdapt",  "Java", "neemt alle info op uit UberEastScraperAPI")
Component("RestaurantApi1.2Implementatie", "TripAdvisorAdapt", "Java", "neemt alle info op uit TripAdvisorAPI")
}

System_Ext("RestaurantApi1","UberEastScraperAPI")
System_Ext("RestaurantApi2","TripAdvisorAPI")

frontend --> restaurentController1 : "/GET Voor het ophalen van restaurants in de buurt 1"

restaurentController1 --> restaurentService1 : "aanroep voor ophalen restaurants 2"

restaurentService1 --> "RestaurantApi1Implementatie" : "Geeft de aanvraag aan beschikbare api 3"
restaurentService1 --> "RestaurantApi1.2Implementatie" : "Geeft de aanvraag aan beschikbare api"

"RestaurantApi1Implementatie" --> "RestaurantApi1" : "Haalt data op met evt params[Json] 4"
"RestaurantApi1.2Implementatie"--> "RestaurantApi2" : "Haalt data op met evt params[Json]"

"RestaurantApi2" --> "RestaurantApi1.2Implementatie" : "returned data in eigen format "
"RestaurantApi1" --> "RestaurantApi1Implementatie" : "returned data in eigen format 5"

"RestaurantApi1.2Implementatie" --> "RestaurantApi1.2Implementatie" : "formateerd data naar service format[Json]"
"RestaurantApi1Implementatie" --> "RestaurantApi1Implementatie" : "formateerd data naar service format[Json] 6"

"RestaurantApi1Implementatie" --> "restaurentService1" : "Returned data in bruikbare format[Json] 7"
"RestaurantApi1.2Implementatie" --> "restaurentService1" : "Returned data in bruikbare format[Json]"

@enduml